'Aさん、Bさん２人の場合
@startuml

actor A as Aさん
participant MagicOnion as サーバー
actor B as Bさん

'連番の自動付与
autonumber

note over サーバー : 参加者：なし

'Aさんが入室
Aさん -> サーバー : 部屋に入室
サーバー --> Aさん : 「部屋に入室しました」

note over サーバー : 参加者：Aさん

'Bさんが入室
Bさん -> サーバー : 部屋に入室
サーバー --> Bさん : 「部屋に入室しました」
サーバー --> Aさん : 「 Bさん が入室しました」

note over サーバー : 参加者：Aさん,Bさん

@enduml

'A~Cさん３人の場合
@startuml

actor A as Aさん
actor B as Bさん
participant MagicOnion as サーバー
actor C as Cさん

'連番の自動付与
autonumber

note over サーバー : 参加者：なし

'Aさんが入室
Aさん -> サーバー : 部屋に入室
サーバー -> サーバー : Aさんの入室処理
サーバー --> Aさん : 「部屋に入室しました」

note over サーバー : 参加者：Aさん

'Bさんが入室
Bさん -> サーバー : 部屋に入室
サーバー -> サーバー : Bさんの入室処理
サーバー --> Bさん : 「部屋に入室しました」
サーバー --> Aさん : 「 Bさん が入室しました」

note over サーバー : 参加者：Aさん,Bさん

'Cさんが入室
Cさん -> サーバー : 部屋に入室
サーバー -> サーバー : Cさんの入室処理
サーバー --> Cさん : 「部屋に入室しました」
サーバー --> Aさん : 「 Cさん が入室しました」
サーバー --> Bさん : 「 Cさん が入室しました」

note over サーバー : 参加者：Aさん,Bさん,Cさん

'サーバーから各プレイヤーに向けた他プレイヤーの入室報告が
'増えて負担になることがわかりました。

@enduml